title: The Modern School
subtitle: Independent Black Education in Harlem, 1934-1998
author:
  name:
  email: harlemeducationhistory@tc.columbia.edu
description:
  Mildred L. Johnson and her colleagues led The Modern School, an independent Black school in Harlem, from 1934 to 1998. This site documents their work and the memories of members of The Modern School community.
url: 
baseurl: "/modern"

# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  doc: # name of collection
    output: true # makes sure pages are output as html files
    layout: "tmsdoc_item" # the layout for the pages to use
    metadata:
      source: "doc.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/doc" # path to the directory of images within `_data`
  photo: # name of collection
    output: true # makes sure pages are output as html files
    layout: "tmsphoto" # the layout for the pages to use
    metadata:
      source: "photo.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/photo" # path to the directory of images within `_data`
  oh: # name of collection
    output: true # makes sure pages are output as html files
    layout: "oh_item" # the layout for the pages to use
    metadata:
      source: "oh.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/oh" # path to the directory of images within `_data`
  process: # name of collection
    output: true # makes sure pages are output as html files
    layout: "tmsdoc_item" # the layout for the pages to use
    metadata:
      source: "process.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/process" # path to the directory of images within `_data`
# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: "/search/index.json" # file the index will get written to
    collections:
      doc:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - _date
          - contributor
          - names
          - _tags
          - description
      photo:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - _date
          - contributor
          - names
          - _tags
          - description
      oh:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - _date
          - description
          - interviewer
          - location
          - _tags
          - names
      process:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
        - label
        - _date
        - contributor
        - names
        - _tags
        - description
        - names





# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: "Collections"
    link: "/collection/"
  - label: "Essays"
    sub:
      - label: "Flowers Essay"
        link: "/exhibits/flowers/"
      - label: "Luna Essay"
        link: "/exhibits/luna/"
      - label: "Taylor Essay"
        link: "/exhibits/taylor/"
      - label: "Erickson Essay"
        link: "/exhibits/erickson/"
  - label: "Search"
    link: "/search/"
  - label: "About"
    link: "/about/"
  - label: "More"
    link: "/more/"
